# Generated by Django 4.2 on 2023-04-18 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Deben ser 3 letras mayusculas seguidas de 3 numeros",
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "clase",
                    models.CharField(
                        choices=[
                            ("CMP", "Camperas"),
                            ("BZS", "Buzos"),
                            ("REM", "Remeras"),
                            ("RPI", "Ropa interior"),
                            ("CLZ", "Calzado"),
                        ],
                        max_length=3,
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("talle", models.CharField(max_length=10)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("C", "Compra"), ("V", "Venta")], max_length=1
                    ),
                ),
                ("fecha", models.DateField()),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inventory.producto",
                    ),
                ),
            ],
        ),
    ]
